// src/app/leaderboard/page.tsx
'use client';

import React, { useState, useMemo } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {
  Trophy,
  UsersThree,
  User,
  SealCheck,
  MagnifyingGlass,
  ArrowRight,
  CaretDown,
  CaretUp,
} from '@phosphor-icons/react';
import { Navbar } from '@/components/layout/Navbar';
import { CrtScanlines } from '@/components/layout/CrtScanlines';
import { PixelBadge } from '@/components/ui/PixelBadge';
import { useGameStore } from '@/store/useGameStore';
import {
  INITIAL_LEADERBOARD_USERS,
  INITIAL_LEADERBOARD_GROUPS,
  AVATAR_OPTIONS,
} from '@/data/mockData';
import { soundEngine } from '@/lib/sound';
import { LeaderboardUser, LeaderboardGroup } from '@/types/game';

export default function LeaderboardPage() {
  const participant = useGameStore((state) => state.participant);
  const soundEnabled = useGameStore((state) => state.soundEnabled);

  const [activeTab, setActiveTab] = useState<'individu' | 'kelompok'>('individu');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [expandedGroupId, setExpandedGroupId] = useState<string | null>('group-03');

  // Compute live individual leaderboard including current user
  const individualList: LeaderboardUser[] = useMemo(() => {
    const currentUserEntry: LeaderboardUser = {
      id: 'current-user',
      rank: 0,
      name: `${participant.name} (Kamu)`,
      nim: participant.nim,
      faculty: participant.faculty,
      prodi: participant.prodi,
      avatar: participant.avatar,
      totalXp: participant.totalXp,
      stampsCount: participant.completedBooths.length,
      completedFloors: Math.floor(participant.completedBooths.length / 2),
      isCurrentUser: true,
      groupId: participant.groupId || 'group-03',
      groupName: 'Genius 03',
    };

    const others = INITIAL_LEADERBOARD_USERS.filter((u) => u.nim !== participant.nim);
    const combined = [...others, currentUserEntry];
    combined.sort((a, b) => b.totalXp - a.totalXp);

    return combined.map((item, index) => ({
      ...item,
      rank: index + 1,
    }));
  }, [participant]);

  // Compute live group leaderboard
  const groupList: LeaderboardGroup[] = useMemo(() => {
    const groups = INITIAL_LEADERBOARD_GROUPS.map((group) => {
      const updatedMembers = group.members.map((member) => {
        if (member.isCurrentUser || member.nim === participant.nim) {
          return {
            ...member,
            name: `${participant.name} (Kamu)`,
            nim: participant.nim,
            totalXp: participant.totalXp,
            stampsCount: participant.completedBooths.length,
            avatar: participant.avatar,
            isCurrentUser: true,
          };
        }
        return member;
      });

      const totalXp = updatedMembers.reduce((acc, m) => acc + m.totalXp, 0);
      const avgXp = Math.round(totalXp / updatedMembers.length);
      const totalStamps = updatedMembers.reduce((acc, m) => acc + m.stampsCount, 0);
      const totalStampsAvg = Number((totalStamps / updatedMembers.length).toFixed(1));

      return {
        ...group,
        members: updatedMembers,
        totalXp,
        avgXp,
        totalStampsAvg,
      };
    });

    groups.sort((a, b) => b.avgXp - a.avgXp);
    return groups.map((g, index) => ({
      ...g,
      rank: index + 1,
    }));
  }, [participant]);

  const filteredIndividuals = individualList.filter(
    (user) =>
      user.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      user.nim.toLowerCase().includes(searchQuery.toLowerCase()) ||
      user.prodi.toLowerCase().includes(searchQuery.toLowerCase()) ||
      user.faculty.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const currentUserRankInfo = individualList.find((u) => u.isCurrentUser);

  const getRankBadge = (rank: number) => {
    if (rank === 1) {
      return (
        <span className="w-7 h-7 rounded-md bg-[#f0d060] text-[#1b120a] flex items-center justify-center font-pixel text-xs font-black shrink-0">
          1
        </span>
      );
    }
    if (rank === 2) {
      return (
        <span className="w-7 h-7 rounded-md bg-[#d4d4d8] text-[#18181b] flex items-center justify-center font-pixel text-xs font-black shrink-0">
          2
        </span>
      );
    }
    if (rank === 3) {
      return (
        <span className="w-7 h-7 rounded-md bg-[#d97706] text-white flex items-center justify-center font-pixel text-xs font-black shrink-0">
          3
        </span>
      );
    }
    return (
      <span className="w-7 h-7 rounded-md bg-[#170f07] text-[#a08060] border border-[#5a3a18] flex items-center justify-center font-pixel text-xs font-bold shrink-0">
        {rank}
      </span>
    );
  };

  const getAvatarImage = (avatarId: string) => {
    const opt = AVATAR_OPTIONS.find((a) => a.id === avatarId);
    return opt ? opt.avatarImage : '/character-cowok-avatar.png';
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#2d1b0e] text-[#f0e0c0] w-full overflow-x-hidden">
      <CrtScanlines />
      <Navbar />

      <main className="w-full max-w-4xl mx-auto px-3 sm:px-6 py-4 sm:py-6 flex-1 space-y-4 overflow-x-hidden">
        {/* Simple Header */}
        <div className="flex items-center justify-between gap-3">
          <div>
            <h1 className="font-pixel text-lg sm:text-2xl font-bold text-[#f0d060] flex items-center gap-2">
              <Trophy size={24} weight="fill" className="text-[#f0d060] shrink-0" />
              <span>Papan Peringkat</span>
            </h1>
            <p className="font-sans text-xs text-[#c4956a] mt-0.5">
              Peringkat perolehan poin orientasi kampus.
            </p>
          </div>

          <Link href="/play" className="shrink-0">
            <button
              onClick={() => soundEnabled && soundEngine.playClick()}
              className="rpg-btn-primary py-2 px-3 text-xs font-pixel font-bold flex items-center gap-1.5"
            >
              <span>Main</span>
              <ArrowRight size={14} weight="bold" />
            </button>
          </Link>
        </div>

        {/* Current User Highlight Card */}
        {currentUserRankInfo && (
          <div className="sdv-card-gold p-3.5 sm:p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-3 min-w-0">
              <div className="w-12 h-12 rounded-lg overflow-hidden bg-[#170f07] border-2 border-[#f0d060] shrink-0 relative">
                <Image
                  src={getAvatarImage(participant.avatar)}
                  alt="Avatar"
                  fill
                  className="object-cover"
                />
              </div>
              <div className="min-w-0">
                <div className="flex items-center gap-1.5">
                  <span className="font-pixel text-[9px] text-[#7ec850] uppercase">
                    Posisi Kamu:
                  </span>
                  <PixelBadge variant="gold" size="sm">
                    #{currentUserRankInfo.rank}
                  </PixelBadge>
                </div>
                <h3 className="font-pixel text-xs sm:text-sm font-bold text-white truncate">
                  {participant.name}
                </h3>
                <p className="font-sans text-[11px] text-[#c4956a] truncate">
                  {participant.nim} • {participant.prodi}
                </p>
              </div>
            </div>

            <div className="flex items-center justify-between sm:justify-end gap-3 border-t sm:border-t-0 sm:border-l border-[#5a3a18] pt-2 sm:pt-0 sm:pl-4">
              <div className="text-center">
                <div className="font-pixel text-xs text-[#f0d060] font-bold">
                  {participant.totalXp} XP
                </div>
                <div className="text-[9px] font-sans text-[#a08060]">Poin</div>
              </div>
              <div className="w-[1px] h-6 bg-[#5a3a18]" />
              <div className="text-center">
                <div className="font-pixel text-xs text-[#7ec850] font-bold">
                  {participant.completedBooths.length}/18
                </div>
                <div className="text-[9px] font-sans text-[#a08060]">Stempel</div>
              </div>
            </div>
          </div>
        )}

        {/* Tab Selector (Strict Grid 2-cols, No horizontal scroll) */}
        <div className="grid grid-cols-2 gap-2 w-full">
          <button
            type="button"
            onClick={() => {
              setActiveTab('individu');
              if (soundEnabled) soundEngine.playSelect();
            }}
            className={`w-full py-2.5 px-3 rounded-lg font-pixel text-xs font-bold border transition-all flex items-center justify-center gap-2 cursor-pointer ${
              activeTab === 'individu'
                ? 'bg-[#3d7828] text-[#f0d060] border-[#f0d060] shadow'
                : 'bg-[#170f07] text-[#a08060] border-[#5a3a18] hover:border-[#8b6f4e]'
            }`}
          >
            <User size={16} weight="bold" />
            <span>Individu</span>
          </button>

          <button
            type="button"
            onClick={() => {
              setActiveTab('kelompok');
              if (soundEnabled) soundEngine.playSelect();
            }}
            className={`w-full py-2.5 px-3 rounded-lg font-pixel text-xs font-bold border transition-all flex items-center justify-center gap-2 cursor-pointer ${
              activeTab === 'kelompok'
                ? 'bg-[#3d7828] text-[#f0d060] border-[#f0d060] shadow'
                : 'bg-[#170f07] text-[#a08060] border-[#5a3a18] hover:border-[#8b6f4e]'
            }`}
          >
            <UsersThree size={16} weight="bold" />
            <span>Kelompok</span>
          </button>
        </div>

        {/* TAB 1: INDIVIDU */}
        {activeTab === 'individu' && (
          <div className="space-y-3 w-full">
            {/* Search Bar */}
            <div className="relative w-full">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Cari nama, NIM, prodi..."
                className="w-full bg-[#170f07] border border-[#5a3a18] focus:border-[#f0d060] rounded-lg px-3 py-2 pl-9 text-xs text-white font-sans outline-none"
              />
              <MagnifyingGlass
                size={16}
                weight="bold"
                className="absolute left-3 top-2.5 text-[#8b6f4e]"
              />
            </div>

            {/* List Cards */}
            <div className="space-y-2 w-full">
              {filteredIndividuals.map((user) => {
                const isMe = user.isCurrentUser;

                return (
                  <div
                    key={user.id}
                    className={`p-3 rounded-xl border flex items-center justify-between gap-2.5 transition-all w-full ${
                      isMe
                        ? 'bg-[#1f3a2b] border-[#f0d060] shadow'
                        : 'bg-[#170f07] border-[#3d2b1e] hover:border-[#5a3a18]'
                    }`}
                  >
                    {/* Left: Rank & Avatar & Info */}
                    <div className="flex items-center gap-2.5 min-w-0">
                      {getRankBadge(user.rank)}

                      <div className="w-9 h-9 rounded-lg overflow-hidden bg-[#281c12] border border-[#8b6f4e] shrink-0 relative">
                        <Image
                          src={getAvatarImage(user.avatar)}
                          alt={user.name}
                          fill
                          className="object-cover"
                        />
                      </div>

                      <div className="min-w-0">
                        <div className="flex items-center gap-1.5">
                          <h4
                            className={`font-pixel text-xs truncate ${
                              isMe ? 'text-white font-bold' : 'text-[#f0e0c0]'
                            }`}
                          >
                            {user.name}
                          </h4>
                          {isMe && (
                            <PixelBadge variant="gold" size="sm">
                              KAMU
                            </PixelBadge>
                          )}
                        </div>
                        <p className="font-sans text-[10px] text-[#a08060] truncate">
                          {user.prodi}
                        </p>
                      </div>
                    </div>

                    {/* Right: Points & Stamp count */}
                    <div className="text-right shrink-0">
                      <div className="font-pixel text-xs text-[#f0d060] font-bold">
                        {user.totalXp} XP
                      </div>
                      <div className="font-sans text-[10px] text-[#7ec850]">
                        {user.stampsCount}/18 Stempel
                      </div>
                    </div>
                  </div>
                );
              })}

              {filteredIndividuals.length === 0 && (
                <div className="p-6 text-center bg-[#170f07] border border-[#5a3a18] rounded-xl font-sans text-xs text-[#a08060]">
                  Tidak ada peserta yang cocok.
                </div>
              )}
            </div>
          </div>
        )}

        {/* TAB 2: KELOMPOK */}
        {activeTab === 'kelompok' && (
          <div className="space-y-2.5 w-full">
            {groupList.map((group) => {
              const isExpanded = expandedGroupId === group.id;
              const hasMe = group.members.some((m) => m.isCurrentUser);

              return (
                <div
                  key={group.id}
                  className={`sdv-card transition-all overflow-hidden w-full ${
                    hasMe ? 'border-[#f0d060]' : ''
                  }`}
                >
                  {/* Accordion Header */}
                  <button
                    type="button"
                    onClick={() => {
                      setExpandedGroupId(isExpanded ? null : group.id);
                      if (soundEnabled) soundEngine.playSelect();
                    }}
                    className="w-full p-3 sm:p-4 flex items-center justify-between gap-3 text-left cursor-pointer"
                  >
                    <div className="flex items-center gap-2.5 min-w-0">
                      {getRankBadge(group.rank)}

                      <div className="min-w-0">
                        <div className="flex items-center gap-1.5">
                          <h3 className="font-pixel text-xs font-bold text-white truncate">
                            {group.name}
                          </h3>
                          {hasMe && (
                            <PixelBadge variant="gold" size="sm">
                              KAMU
                            </PixelBadge>
                          )}
                        </div>
                        <p className="font-sans text-[11px] text-[#a08060] truncate">
                          {group.members.length} Anggota
                        </p>
                      </div>
                    </div>

                    {/* Right Stats & Expand Icon */}
                    <div className="flex items-center gap-3 shrink-0">
                      <div className="text-right">
                        <div className="font-pixel text-xs font-bold text-[#f0d060]">
                          {group.avgXp} XP
                        </div>
                        <div className="font-sans text-[9px] text-[#7ec850]">
                          Rata-rata
                        </div>
                      </div>

                      <div className="p-1 bg-[#170f07] border border-[#5a3a18] rounded text-[#f0d060]">
                        {isExpanded ? (
                          <CaretUp size={14} weight="bold" />
                        ) : (
                          <CaretDown size={14} weight="bold" />
                        )}
                      </div>
                    </div>
                  </button>

                  {/* Accordion Content (Members Breakdown) */}
                  {isExpanded && (
                    <div className="bg-[#170f07] border-t border-[#5a3a18] p-3 space-y-2 animate-in fade-in">
                      <div className="text-[9px] font-pixel text-[#a08060] uppercase border-b border-[#3d2b1e] pb-1">
                        Anggota Kelompok:
                      </div>

                      <div className="space-y-1.5">
                        {group.members.map((member) => (
                          <div
                            key={member.id}
                            className={`p-2 rounded-lg border flex items-center justify-between gap-2 ${
                              member.isCurrentUser
                                ? 'bg-[#1f3a2b] border-[#7ec850] text-[#f0ffd0]'
                                : 'bg-[#23160c] border-[#3d2b1e] text-[#e0d0b0]'
                            }`}
                          >
                            <div className="flex items-center gap-2 min-w-0">
                              <div className="w-7 h-7 rounded-md overflow-hidden bg-[#170f07] border border-[#8b6f4e] shrink-0 relative">
                                <Image
                                  src={getAvatarImage(member.avatar)}
                                  alt={member.name}
                                  fill
                                  className="object-cover"
                                />
                              </div>
                              <div className="min-w-0">
                                <div className="font-pixel text-[10px] font-bold truncate">
                                  {member.name}
                                </div>
                                <div className="font-sans text-[9px] text-[#a08060] truncate">
                                  {member.prodi}
                                </div>
                              </div>
                            </div>

                            <div className="text-right shrink-0">
                              <div className="font-pixel text-[10px] text-[#f0d060] font-bold">
                                {member.totalXp} XP
                              </div>
                              <div className="font-sans text-[9px] text-[#7ec850]">
                                {member.stampsCount} Stempel
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}

// frontend/admin/pages/buddy/leaderboard.vue
<template>
  <div class="space-y-3 pb-8 select-none font-sans text-[#f0e0c0]">
    <!-- Compact Header Banner -->
    <div class="sdv-card-gold p-3 space-y-2">
      <div class="flex items-center justify-between">
        <div>
          <span class="border border-[#f0d060] bg-[#1a1008] px-1.5 py-0.5 text-[8px] font-pixel text-[#f0d060] uppercase tracking-wider rounded">
            KLASEMEN KAMPUS
          </span>
          <h1 class="font-pixel text-xs sm:text-sm text-[#fef08a] font-bold mt-1">
            LEADERBOARD GENIUS 2026
          </h1>
        </div>
        <div class="w-8 h-8 rounded-lg bg-[#281c12] border border-[#f0d060] flex items-center justify-center shrink-0 shadow">
          <Trophy class="h-4 w-4 text-[#f0d060]" />
        </div>
      </div>

      <!-- Live / Freeze Status Pill -->
      <div class="flex items-center justify-between pt-1 border-t border-[#5a3a18] text-[10px] font-mono">
        <div class="flex items-center gap-1.5">
          <span class="w-2 h-2 rounded-full bg-[#22c55e] animate-pulse"></span>
          <span class="text-[#86efac]">LIVE CLOUD SYNC</span>
        </div>
        <span class="text-[#c4956a]">
          Regu Anda: <strong class="text-[#f0d060] font-pixel text-[9px]">{{ myTeamRankLabel }}</strong>
        </span>
      </div>
    </div>

    <!-- Tab Switcher: Kelompok vs Individu (Stardew Style) -->
    <div class="grid grid-cols-2 gap-2 font-mono text-xs p-1 bg-[#170f07] border-2 border-[#5a3a18] rounded-xl">
      <button
        type="button"
        @click="activeTab = 'teams'"
        :class="[
          'py-2 px-3 rounded-lg font-pixel text-[9px] sm:text-[10px] flex items-center justify-center gap-1.5 cursor-pointer transition-all',
          activeTab === 'teams'
            ? 'rpg-btn-primary shadow text-white'
            : 'text-[#c4956a] hover:text-white'
        ]"
      >
        <Users class="h-3.5 w-3.5" />
        <span>KLASEMEN REGU</span>
      </button>

      <button
        type="button"
        @click="activeTab = 'individuals'"
        :class="[
          'py-2 px-3 rounded-lg font-pixel text-[9px] sm:text-[10px] flex items-center justify-center gap-1.5 cursor-pointer transition-all',
          activeTab === 'individuals'
            ? 'rpg-btn-primary shadow text-white'
            : 'text-[#c4956a] hover:text-white'
        ]"
      >
        <User class="h-3.5 w-3.5" />
        <span>INDIVIDU MABA</span>
      </button>
    </div>

    <!-- Search Input -->
    <div class="relative">
      <input
        v-model="searchQuery"
        type="text"
        :placeholder="activeTab === 'teams' ? 'Cari nama kelompok...' : 'Cari nama maba atau NIM...'"
        class="w-full bg-[#170f07] border-2 border-[#5a3a18] focus:border-[#f0d060] rounded-lg pl-8 pr-3 py-2 text-xs text-white outline-none font-mono placeholder:text-[#a08060]"
      />
      <Search class="h-4 w-4 text-[#f0d060] absolute left-2.5 top-2.5" />
    </div>

    <!-- TAB 1: KLASEMEN REGU (TEAMS) -->
    <div v-if="activeTab === 'teams'" class="space-y-3">
      <!-- Loading indicator -->
      <div v-if="loading" class="sdv-card p-6 text-center text-[#c4956a] font-mono text-xs">
        <div class="inline-block w-5 h-5 border-2 border-[#f0d060] border-t-transparent rounded-full animate-spin mb-2"></div>
        <div>Memuat data klasemen kampus...</div>
      </div>

      <!-- Top 3 Podium (Mini Physical Cards) -->
      <div v-else class="grid grid-cols-3 gap-2 pt-1 pb-1 font-mono">
        <!-- 2nd Place -->
        <div class="sdv-card p-2 text-center flex flex-col justify-end items-center">
          <Medal class="h-5 w-5 text-gray-300 mb-1" />
          <span class="font-pixel text-[7.5px] text-gray-300">#2 PERAK</span>
          <span class="font-sans text-[10px] font-bold text-white line-clamp-1 mt-0.5">{{ rank2Team?.name || '-' }}</span>
          <span class="font-pixel text-[8.5px] text-[#f0d060] font-bold mt-1">{{ rank2Team ? `${rank2Team.score.toLocaleString()} PTS` : '- PTS' }}</span>
        </div>

        <!-- 1st Place (Winner / Highlight) -->
        <div class="sdv-card-gold p-2.5 text-center flex flex-col justify-end items-center scale-105 shadow-xl">
          <Crown class="h-6 w-6 text-[#facc15] mb-1 animate-bounce" />
          <span class="font-pixel text-[8px] text-[#facc15]">#1 EMAS</span>
          <span class="font-sans text-[10.5px] font-bold text-[#fef08a] line-clamp-1 mt-0.5">{{ rank1Team?.name || '-' }}</span>
          <span class="font-pixel text-[9.5px] text-[#86efac] font-bold mt-1">{{ rank1Team ? `${rank1Team.score.toLocaleString()} PTS` : '- PTS' }}</span>
        </div>

        <!-- 3rd Place -->
        <div class="sdv-card p-2 text-center flex flex-col justify-end items-center">
          <Medal class="h-5 w-5 text-[#ea580c] mb-1" />
          <span class="font-pixel text-[7.5px] text-[#fb923c]">#3 PERUNGGU</span>
          <span class="font-sans text-[10px] font-bold text-white line-clamp-1 mt-0.5">{{ rank3Team?.name || '-' }}</span>
          <span class="font-pixel text-[8.5px] text-[#f0d060] font-bold mt-1">{{ rank3Team ? `${rank3Team.score.toLocaleString()} PTS` : '- PTS' }}</span>
        </div>
      </div>

      <!-- Team List -->
      <div v-if="!loading" class="space-y-2">
        <div v-if="filteredTeams.length === 0" class="sdv-card p-4 text-center text-[#c4956a] font-mono text-xs">
          Tidak ada regu yang cocok.
        </div>
        <div
          v-for="team in filteredTeams"
          :key="team.id"
          :class="[
            'p-3 rounded-xl border-2 flex items-center justify-between transition-all',
            isMyTeam(team.id)
              ? 'sdv-card-gold border-[#f0d060] ring-1 ring-[#f0d060] shadow-md'
              : 'sdv-card'
          ]"
        >
          <div class="flex items-center gap-2.5">
            <!-- Rank Badge -->
            <div
              :class="[
                'w-6 h-6 rounded flex items-center justify-center font-pixel text-xs shrink-0',
                team.rank === 1 ? 'bg-[#ca8a04] text-[#140e08] font-bold' :
                team.rank === 2 ? 'bg-gray-400 text-black font-bold' :
                team.rank === 3 ? 'bg-amber-800 text-white font-bold' :
                'bg-[#261a11] text-[#a08060]'
              ]"
            >
              #{{ team.rank }}
            </div>

            <div>
              <div class="flex items-center gap-1.5">
                <span class="font-sans text-xs text-white font-bold">
                  {{ team.name }}
                </span>
                <span
                  v-if="isMyTeam(team.id)"
                  class="font-pixel text-[7px] text-[#f0d060] bg-[#2d1b0e] border border-[#f0d060] px-1.5 py-0.2 rounded"
                >
                  BINAAN ANDA
                </span>
              </div>
              <span class="text-[9.5px] text-[#c4956a] font-mono">
                Kode: {{ team.code }} &bull; {{ team.completedStamps }}/18 Pos
              </span>
            </div>
          </div>

          <div class="text-right shrink-0">
            <span class="font-pixel text-xs text-[#86efac] font-bold block">
              {{ team.score.toLocaleString() }}
            </span>
            <span class="text-[7.5px] text-[#a08060] font-mono">POIN REGU</span>
          </div>
        </div>
      </div>
    </div>

    <!-- TAB 2: KLASEMEN INDIVIDU (INDIVIDUALS) -->
    <div v-else class="space-y-2">
      <!-- Loading indicator -->
      <div v-if="loading" class="sdv-card p-6 text-center text-[#c4956a] font-mono text-xs">
        <div class="inline-block w-5 h-5 border-2 border-[#f0d060] border-t-transparent rounded-full animate-spin mb-2"></div>
        <div>Memuat data mahasiswa kampus...</div>
      </div>
      <div v-else-if="filteredStudents.length === 0" class="sdv-card p-4 text-center text-[#c4956a] font-mono text-xs">
        Tidak ada mahasiswa yang cocok.
      </div>
      <div
        v-else
        v-for="student in filteredStudents"
        :key="student.id"
        :class="[
          'p-3 rounded-xl border-2 flex items-center justify-between transition-all',
          isMyMember(student.id)
            ? 'sdv-card-gold border-[#f0d060]'
            : 'sdv-card'
        ]"
      >
        <div class="flex items-center gap-2.5">
          <!-- Rank Badge -->
          <div
            :class="[
              'w-6 h-6 rounded flex items-center justify-center font-pixel text-xs shrink-0',
              student.rank === 1 ? 'bg-[#ca8a04] text-[#140e08] font-bold' :
              student.rank === 2 ? 'bg-gray-400 text-black font-bold' :
              student.rank === 3 ? 'bg-amber-800 text-white font-bold' :
              'bg-[#261a11] text-[#a08060]'
            ]"
          >
            #{{ student.rank }}
          </div>

          <img
            :src="student.avatarUrl"
            :alt="student.fullName"
            class="w-8 h-8 rounded-lg border border-[#f0d060] bg-black/40 shrink-0"
          />

          <div>
            <div class="flex items-center gap-1.5">
              <span class="font-sans text-xs text-white font-bold">
                {{ student.fullName }}
              </span>
              <span
                v-if="isMyMember(student.id)"
                class="font-pixel text-[7px] text-[#86efac] bg-[#172513] border border-[#22c55e]/60 px-1 py-0.2 rounded"
              >
                ANGGOTA SAYA
              </span>
            </div>
            <span class="text-[9.5px] text-[#c4956a] font-mono">
              NIM {{ student.username }} &bull; <strong class="text-[#f0d060]">{{ student.prodi }}</strong> &bull; {{ student.teamName }}
            </span>
          </div>
        </div>

        <div class="text-right shrink-0">
          <span class="font-pixel text-xs text-[#86efac] font-bold block">
            {{ student.totalXp.toLocaleString() }} XP
          </span>
          <span class="text-[8px] text-[#f0d060] font-mono">
            {{ student.stamps }} Stempel
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import {
  Trophy,
  Users,
  User,
  Search,
  Crown,
  Medal,
} from "lucide-vue-next";
import { useAuth } from "@/composables/useAuth";
import { useApi } from "@/composables/useApi";
import { useRealtime } from "@/composables/useRealtime";

const { user } = useAuth();
const api = useApi();
const { onLeaderboardUpdate } = useRealtime();

const activeTab = ref<"teams" | "individuals">("teams");
const searchQuery = ref("");
const loading = ref(true);

interface TeamRankItem {
  id: string;
  rank: number;
  name: string;
  code: string;
  score: number;
  completedStamps: number;
  buddyName: string;
}

interface StudentRankItem {
  id: string;
  rank: number;
  fullName: string;
  username: string;
  prodi: string;
  teamName: string;
  teamId?: string;
  totalXp: number;
  stamps: number;
  avatarUrl: string;
}

const allTeams = ref<TeamRankItem[]>([]);
const allStudents = ref<StudentRankItem[]>([]);

const rank1Team = computed(() => allTeams.value.find((t) => t.rank === 1) || allTeams.value[0]);
const rank2Team = computed(() => allTeams.value.find((t) => t.rank === 2) || allTeams.value[1]);
const rank3Team = computed(() => allTeams.value.find((t) => t.rank === 3) || allTeams.value[2]);

const currentTeamId = computed(() => {
  return user.value?.teamId || "";
});

const isMyTeam = (teamId: string) => {
  if (!currentTeamId.value) return false;
  return teamId === currentTeamId.value;
};

const isMyMember = (studentId: string) => {
  const student = allStudents.value.find((s) => s.id === studentId);
  if (!currentTeamId.value || !student?.teamId) return false;
  return student.teamId === currentTeamId.value;
};

const myTeamRankLabel = computed(() => {
  if (!currentTeamId.value) {
    const first = allTeams.value[0];
    return first ? `#${first.rank} (${first.score.toLocaleString()} PTS)` : "#-";
  }
  const found = allTeams.value.find((t) => t.id === currentTeamId.value);
  if (found) return `#${found.rank} (${found.score.toLocaleString()} PTS)`;
  return "#-";
});

const filteredTeams = computed(() => {
  if (!searchQuery.value.trim()) return allTeams.value;
  const q = searchQuery.value.toLowerCase();
  return allTeams.value.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.code.toLowerCase().includes(q) ||
      t.buddyName.toLowerCase().includes(q)
  );
});

const filteredStudents = computed(() => {
  if (!searchQuery.value.trim()) return allStudents.value;
  const q = searchQuery.value.toLowerCase();
  return allStudents.value.filter(
    (s) =>
      s.fullName.toLowerCase().includes(q) ||
      s.username.includes(q) ||
      s.teamName.toLowerCase().includes(q)
  );
});

async function fetchLeaderboard() {
  loading.value = true;
  try {
    const res = await api.get<{ success: boolean; data: any }>("/api/leaderboard");
    if (res.success && res.data) {
      const rawTeams = res.data.teamLeaderboard || [];
      allTeams.value = rawTeams.map((t: any, idx: number) => ({
        id: t.teamId,
        rank: t.rank || idx + 1,
        name: t.teamName || "Genius Tim",
        code: t.teamCode || "-",
        score: Number(t.totalScore || 0),
        completedStamps: Math.min(18, Math.floor(Number(t.totalScore || 0) / 100)),
        buddyName: t.buddyName || "Buddy",
      }));

      const rawParticipants = res.data.participantLeaderboard || [];
      allStudents.value = rawParticipants.map((p: any, idx: number) => ({
        id: p.participantId,
        rank: p.rank || idx + 1,
        fullName: p.participantName || "Mahasiswa",
        username: p.username || "-",
        prodi: p.characterClass || p.characterTitle || "Informatika",
        teamName: p.teamName || "Genius",
        teamId: p.teamId,
        totalXp: Number(p.totalScore || 0),
        stamps: Math.min(18, Math.floor(Number(p.totalScore || 0) / 50)),
        avatarUrl: p.gender === "FEMALE" ? "/character-cewek-avatar.png" : "/character-cowok-avatar.png",
      }));
    }
  } catch (err: any) {
    console.error("Gagal memuat leaderboard buddy:", err);
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  fetchLeaderboard();
  onLeaderboardUpdate(() => {
    fetchLeaderboard();
  });
});
</script>
