// frontend/user/src/components/minigames/MiniGameContainer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Booth } from '@/types/game';
import TtsGame from './TtsGame.vue';
import TebakKataGame from './TebakKataGame.vue';
import TebakPosisiGame from './TebakPosisiGame.vue';
import MemoryMatchGame from './MemoryMatchGame.vue';
import KuisCepatGame from './KuisCepatGame.vue';
import BenarSalahGame from './BenarSalahGame.vue';
import TebakGambarGame from './TebakGambarGame.vue';
import KuisBalapanGame from './KuisBalapanGame.vue';

interface Props {
  booth: Booth;
  isCompleted?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isCompleted: false,
});

const emit = defineEmits<{
  (e: 'complete', score: number, totalQuestions: number): void;
}>();

const gameType = computed(() => props.booth.tipe_game || props.booth.type || 'kuis_cepat');

const handleComplete = (score: number, totalQuestions: number) => {
  emit('complete', score, totalQuestions);
};
</script>

<template>
  <TtsGame
    v-if="gameType === 'tts'"
    :content="props.booth.ttsContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <TebakKataGame
    v-else-if="gameType === 'tebak_kata'"
    :content="props.booth.tebakKataContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <TebakPosisiGame
    v-else-if="gameType === 'tebak_posisi'"
    :content="props.booth.tebakPosisiContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <TebakGambarGame
    v-else-if="gameType === 'tebak_gambar'"
    :content="props.booth.tebakGambarContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <KuisBalapanGame
    v-else-if="gameType === 'kuis_balapan'"
    :content="props.booth.kuisBalapanContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <MemoryMatchGame
    v-else-if="gameType === 'memory_match'"
    :content="props.booth.memoryMatchContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <BenarSalahGame
    v-else-if="gameType === 'benar_salah'"
    :content="props.booth.benarSalahContent"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
  <KuisCepatGame
    v-else
    :content="props.booth.kuisCepatContent"
    :fallbackQuestions="props.booth.questions"
    :isCompleted="props.isCompleted"
    @complete="handleComplete"
  />
</template>

// src/components/minigames/MiniGameContainer.tsx
'use client';

import React from 'react';
import { Booth } from '@/types/game';
import { TtsGame } from './TtsGame';
import { TebakKataGame } from './TebakKataGame';
import { TebakPosisiGame } from './TebakPosisiGame';
import { TebakGambarGame } from './TebakGambarGame';
import { KuisBalapanGame } from './KuisBalapanGame';
import { MemoryMatchGame } from './MemoryMatchGame';
import { KuisCepatGame } from './KuisCepatGame';
import { BenarSalahGame } from './BenarSalahGame';

interface MiniGameContainerProps {
  booth: Booth;
  onComplete: (score: number, totalQuestions: number) => void;
  isCompleted?: boolean;
}

export const MiniGameContainer: React.FC<MiniGameContainerProps> = ({
  booth,
  onComplete,
  isCompleted = false,
}) => {
  const gameType = booth.tipe_game || booth.type || 'kuis_cepat';

  switch (gameType) {
    case 'tts':
      return (
        <TtsGame
          content={booth.ttsContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'tebak_kata':
      return (
        <TebakKataGame
          content={booth.tebakKataContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'tebak_posisi':
      return (
        <TebakPosisiGame
          content={booth.tebakPosisiContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'tebak_gambar':
      return (
        <TebakGambarGame
          content={booth.tebakGambarContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'kuis_balapan':
      return (
        <KuisBalapanGame
          content={booth.kuisBalapanContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'memory_match':
      return (
        <MemoryMatchGame
          content={booth.memoryMatchContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'benar_salah':
      return (
        <BenarSalahGame
          content={booth.benarSalahContent}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );

    case 'kuis_cepat':
    case 'kuis':
    default:
      return (
        <KuisCepatGame
          content={booth.kuisCepatContent}
          fallbackQuestions={booth.questions}
          onComplete={onComplete}
          isCompleted={isCompleted}
        />
      );
  }
};
